apiVersion: apps/v1
kind: Deployment
metadata:
  name: htk-cluster-config-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: htk-cluster-config-operator
  template:
    metadata:
      labels:
        name: htk-cluster-config-operator
    spec:
      serviceAccountName: htk-cluster-config-operator
      containers:
        - name: htk-cluster-config-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - htk-cluster-config-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "htk-cluster-config-operator"
